[tool.poetry]
name = "ts_featurelab"
version = "0.1.0"
description = ""
authors = ["Павел Чеканов <hydrophonyx@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
polars = "^1.40.1"
PyWavelets = "^1.8.0"
numpy = ">=1.23,<2.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
